### ISSUE TITLE
Window undefined with webpack

### ISSUE THREAD

**Issue by benjipott** [smilefam/SendBird-SDK-JavaScript#1]
on 2.4.* ReferenceError: window is not defined
use commonJs syntax

**Comment by sf-james-kim** [comment]
@benjipott 

Please tell me the version of your SDK.
I recommanded using the latest SDK version 2.4.10.

**Comment by benjipott** [comment]
2.4.10
just 2.3.0 looks good

**Comment by sf-james-kim** [comment]
@benjipott 
Please download SDK version 2.4.11.
The problem will be solved by this version.

**Comment by benjipott** [comment]
ReferenceError: navigator is not defined :/

**Comment by sf-james-kim** [comment]
Tell me about where you are using this.
The problem will be solved in version 2.4.12 that is going to be updated this week.

**Comment by sf-james-kim** [comment]
@benjipott 

Please download lastest SDK version 2.4.12.
