### ISSUE TITLE
Provide unminified SDK file

### ISSUE THREAD

**Issue by kennym** [smilefam/SendBird-SDK-JavaScript#10]
Could you share the unminified JS file in order to send pull requests and get an idea of how it works?

**Comment by hareeqi** [comment]
second that

**Comment by fozzle** [comment]
thirded. Also we could more easily make modifications if needed without waiting around for Sendbird to. Doesn't make any sense not to!

**Comment by fozzle** [comment]
FWIW y'all it could hardly be considered minified as they left all the names intact.

https://gist.github.com/fozzle/f7f67bcc0a6d372dc448cf236a9445f1

**Comment by kennym** [comment]
@fozzle thanks for that! No documentation though...

**Comment by kennym** [comment]
better than nothing I guess.

**Comment by kennym** [comment]
@fozzle I think they've heard us: https://github.com/smilefam/SendBird-SDK-JavaScript/blob/master/SendBird.d.ts

**Comment by sf-jin-ku** [comment]
We decided to offer the typescript header but not a non-minified version for public.
It should be available for paid plan customers who need in development phases.
Sorry again.

**Comment by alizahid** [comment]
Is this not the source? https://github.com/smilefam/SendBird-JavaScript/blob/master/basic-sample/static/lib/SendBird.js
