### ISSUE TITLE
Cannot retrieve group channel after send bird connect

### ISSUE THREAD

**Issue by dkiziryan-chegg** [smilefam/SendBird-SDK-JavaScript#100]
Hi SB,

We are running into an issue retrieving a groupchannel when launching are app.

Steps to reproduce:

1. Create sendbird user
2. Create group channel
3. SB.connect
4. in SB.connect callback call SB.GroupChannel.getChannel
5. see 400 returned from sendBird, error code was 0, message was SendBirdException

![screen shot 2018-12-11 at 3 21 11 pm](https://user-images.githubusercontent.com/35113932/49836692-6e0b8c00-fd58-11e8-9ff2-437ad4df7232.png)

**Comment by Alchemist85K** [comment]
Hi @dkiziryan-chegg 
Thank you for your interest in SendBird SDK. :)

Do you use SendBird JavaScript SDK for all the processes you describe?
I recommend the following methods.

1. SB.connect (If the user does not exist, it'll be created)
2. create GroupChannel using JS SDK (sb.GroupChannel.createChannel)
3. get GroupChannel (sb.GroupChannel.getChannel)

Could you give me the code, your APP_ID, and channelUrl?

**Comment by dkiziryan-chegg** [comment]
Hi  @Alchemist85K,

We use platform API to query user and create one if necessary. Then we create the groupChannel with the user. All of this is done in our server side app.

Then on the client side we connect using the JS sdk. 

From my original post 1-2 is server side, and with the return data 3-5 happens client side. 

Regarding giving code, I cant really do that. 

Regarding app id, is possible to provide that via support ticket and you can get it from there?

**Comment by Alchemist85K** [comment]
I tested it the way that you told me, but it works well. The screenshots below is my test result.

Please, check out the following.
1. When you create GroupChannel, is the user included as a member?
2. When you call getChannel(), do you pass the url of channel as the first parameter?

![image](https://user-images.githubusercontent.com/6028833/49839652-58977000-fdf3-11e8-9a6b-3e8664ce0029.png)
![image](https://user-images.githubusercontent.com/6028833/49839657-60571480-fdf3-11e8-8983-9d322d038bd6.png)

**Comment by dkiziryan-chegg** [comment]
When you create GroupChannel, is the user included as a member? yes we create channel and pass user_ids list as part of the request (followed the docs here https://docs.sendbird.com/platform/group_channel#3_create_a_channel)

When you call getChannel(), do you pass the url of channel as the first parameter? yes we do

**Comment by dkiziryan-chegg** [comment]
@Alchemist85K, thanks for the support we were able to figure out whats going on. There was a discrepancy in the app id being used in our server side app and the client side. Thus, the groupchannel was missing.

Whom should close the issue?
