### ISSUE TITLE
Your request domain is not allowed(localhost)

### ISSUE THREAD

**Issue by northkode** [smilefam/SendBird-SDK-JavaScript#107]
How do i resolve this for localhost?
I have tried to add my security domain as http://localhost and just localhost
But i keep getting this error.

**Comment by Alchemist85K** [comment]
@northkode 
Could you give me more information?
- What situation did the error occur?
- What is the code and message of the error?
- Explain the environment in which you develop.

What use is localhost for using SendBird JavaScript SDK?
You can use SendBird JavaScript SDK to chat without using your local server.

Thank you for your interest in SendBird SDK :)

**Comment by northkode** [comment]
I decided to just setup a quick fake http server and use that as localhost seems to not work even after adding to allowed domains in settings
