### ISSUE TITLE
cann't get metadata

### ISSUE THREAD

**Issue by MarwaAbuEssa** [smilefam/SendBird-SDK-JavaScript#11]
hi ,
i had migrated some old data  from my database to sendbird sample app. after last step of migration , i added some metadata to created channels and everything is excellent.
suddenly 2 days ago , i can't get channels metadata at my app !!!!!.
i used to get metadata in app using the following :
`  var keys = ['key1', 'key2'];
			channel.getMetaData(keys, function(response, error) {
				if (error) {
					console.error(error + ' keys channel meta data ');
					return;
					return;
				}
				debugger;
				 console.log(JSON.stringify(response) + ' keys channel meta data '); 
				');  				
			});`
but suddenly response is empty !!!!
i checked servre API method that gets metadata 

`Metadata
POST | https://api.sendbird.com/channel/get_metadata

Get values of metadata keys.

Request
COPY
{
    "auth": API_TOKEN,
    "channel_url": string,      // Channel URL     
    "keys": ["key1", "key2"]   //  Key names
}`

and it works !!! , so channels metadata is exists but javascript sdk method suddenly can't get it !!!!!

please any help 
regards ,

**Comment by sf-victor-lee** [comment]
these bug is fixed.
please update to v3.0.2.

sorry about that,
Victor

**Comment by MarwaAbuEssa** [comment]
yes , i had just upgraded to V3.0.3 and it is solved ,

thanks a million :+1:
