### ISSUE TITLE
many group channels lost ! 

### ISSUE THREAD

**Issue by MarwaAbuEssa** [smilefam/SendBird-SDK-JavaScript#12]
hi, 
i'm using the Javscript SDK V3 and i had created a sample app includes 11 channels , i checked it using your basic-sample .
during my work in a separated app that using this sample app , suddenly the channels reduced to 1 channel !!.
i refreshed your sample app and it disappeared suddenly except this 1 channel !!.
i didn't delete any channel in my separated app .!! . this happened twice and i don't know why.

I checked sendbird dashboard and checked the channels using mesasges link and i found my 4 group channels exists !!!! so why even your basic sample app is not getting it .

any help please ??

**Comment by sf-victor-lee** [comment]
Sorry, basic-sample is using SDK v2 at now.
SDK v3 Sample will have release, soon.

**Comment by MarwaAbuEssa** [comment]
@sf-victor-lee  basic-sample at master branch uses v3 SDK , but i just sent a request to sendbird and they replay about that error and fix it . thanks a lot for your replay
