### ISSUE TITLE
createChannelWithUserIds not implemented?

### ISSUE THREAD

**Issue by bfarrgaynor** [smilefam/SendBird-SDK-JavaScript#14]
I am unable to create a group channel with user ids or anything. I keep getting either 'nothing' back or a 400.

Tried:
```
 sb.GroupChannel.createChannel(userIdsForChannel, false, 'My Chat', '', '', function(channel, error) { ...
```

and... as per the example docs ...

```
var userIds = ['unique_user_id1', 'unique_user_id2'];
// distinct is false 
sb.GroupChannel.createChannelWithUserIds(userIds, false, function(channel, error) {
    if (error) {
        console.error(error);
        return;
    }

    console.log(channel);
});
```

Get either a 400 back or a blank. What gives?

**Comment by sf-jin-ku** [comment]
@bfarrgaynor sorry. we had a typo in the docs.

sb.GroupChannel.createChannelWithUserIds(userIds, false, name, cover_url, data, function(channel, error) {}

This is the right format.

**Comment by bfarrgaynor** [comment]
I was able to create one channel but then it now throws a 400 whenever I try to create more.

What do I send for null cover_url's and null data? 

```
 sb.GroupChannel.createChannelWithUserIds(userIdsForChannel, false, chatName, '', '', function(channel, error) {
```

^ will that work?

Sidenote - we plan on becoming a paid customer - just trying to get this implemented first.

**Comment by sf-jin-ku** [comment]
@bfarrgaynor for other questions, please shoot us at support@sendbird.com!
