### ISSUE TITLE
Connection State

### ISSUE THREAD

**Issue by lukabers** [smilefam/SendBird-SDK-JavaScript#15]
Hello,
We have some problems with the connection status.
When our app goes in background and after a while it comes back as active we can't understand how to check if Sendbird is connected or not.
We tried to use:
`sb.getConnectionState()`

but it always return CLOSED even if it is actually OPEN and we are able to send a message.
Is there any way to check the connection?

Thanks.

**Comment by sf-jin-ku** [comment]
Hi @lukabers,

How do you use JS SDK on mobile platforms?
Do you use React Native or other cross library platforms?

**Comment by lukabers** [comment]
Hi @sf-jin-ku 
we are using JS SDK (V3) on a react-native app.
We followed your example app to build it...
Thanks

**Comment by lukabers** [comment]
Sorry my fault.
You can close this issue... Thanks!|

**Comment by sf-jin-ku** [comment]
Glad that you figured out!

**Comment by osinakayah** [comment]
Please how did you check for the connection status?
