### ISSUE TITLE
GroupChannel.markAsRead doesn't send timestamp

### ISSUE THREAD

**Issue by kfiroo** [smilefam/SendBird-SDK-JavaScript#17]
Hey,
I'm having trouble marking a channel as read after receiving a message.
I might be going at the completely the wrong way, I'd love to get some feedback.

I need to constantly show a list of users in a GroupChannel that read the last message (something like Facebook messenger..)

In order to get this I needed to do a few things:
1. when a user navigates to a chat page and all messages are loaded, call `groupChannel.markAsRead()`
2. after sending a message to a channel call `groupChannel.markAsRead()`
3. after receiving a message call `groupChannel.markAsRead()`

* Not sure all the above are required, as I assume interactions with the API will update the users `lastSeen` timestamp

However, looks like when I call `groupChannel.markAsRead()` nothing really happens.

I know the code is not open sourced, but from when I could gather from the minified version provided in this repo, it looks like there might be a bug.

This is a snippet from the code of `GroupChannel`

```javascript
this.markAsRead = function () {
    markAsReadScheduled = !0
},
this.fireMarkAsRead = function () {
    markAsReadScheduled && (markAsReadScheduled = !1, this.sendMarkAsRead(function (response, error) {
    }))
},
this.sendMarkAsRead = function (timestamp, cb) {
    var _SELF = this;
    return SendBird.getInstance().currentUser ? void APIClient.getInstance().groupChannelMarkAsRead(_SELF.url, SendBird.getInstance().currentUser.userId, timestamp, function (response, error) {
        return error ? void(cb && cb(error)) : (_SELF.unreadMessageCount = 0, void(cb && cb()))
    }) : void cb(null, new SendBirdException("Connection must be made before you mark as read.", SendBirdError.CONNECTION_REQUIRED))
}
```

The API and docs say we should call `markAsRead`, which will cause `fireMarkAsRead` to call `sendMarkAsRead` on the next iteration of `globalTimerLoop`.
Looks like `sendMarkAsRead` expects the first param to be `timestamp` but it is not supplied.
I also couldn't find any other place in the code that provides a default value for this param.

Any feedback would be great!

Thanks

**Comment by sf-jin-ku** [comment]
the timestamp param has never been used and it's been removed :) @kfiroo 
To prevent markasread flooding, we only send one "markasread" per second.
Can you test it out on our latest 3.0.22 to see if it's working?
