### ISSUE TITLE
After connection drops calls to connect never return

### ISSUE THREAD

**Issue by kfiroo** [smilefam/SendBird-SDK-JavaScript#19]
Hey,
After the connection disconnects, I can see the `ConnectionHandler.onReconnectFailed` is called.
I try to connect again but the callback of `sb.connect(userId, accessToken, callback)` is never called.

Any advice?

**Comment by kfiroo** [comment]
Actually after I call `sb.connect` I can see the `ConnectionHandler.onReconnectSucceeded` is called, but the callback still doesn't fire.

**Comment by sf-jin-ku** [comment]
This should be also resolved as well in the latest version
