### ISSUE TITLE
Need unminified version of Sendbird.min.js

### ISSUE THREAD

**Issue by parijatsahai** [smilefam/SendBird-SDK-JavaScript#20]
Where can I find the unminified code for the current version of Sendbird.min.js? I need the unminified version to allow for troubleshooting.

**Comment by kennym** [comment]
I've asked that question before. See #3 and #10

**Comment by sf-jin-ku** [comment]
Sorry. Please refer https://github.com/smilefam/SendBird-SDK-JavaScript/blob/master/SendBird.d.ts for reference and feel free to shoot questions to support@sendbird.com
