### ISSUE TITLE
Not able to initialise SDK 

### ISSUE THREAD

**Issue by ashwathan** [smilefam/SendBird-SDK-JavaScript#22]
Hi,

I  am trying to intergrate  SendBird SDK  in ionic 2 app and here are the steps that I followed

Step 1: Installed SendBird SDK Using npm via this command  "$npm install sendbird --save"

Step 2:  Tried to import sendBird SDK in the modules like "import { SendBird } from 'sendbird';"

Step 3: Then tried to initiate SDK and call sb.connect method, but get this error "SendBird is not defined" in the browser console.

Attached the error stack.

I tried googling but without any luck. Please let me know what I am doing wrong here.

Thanks
![sendbird-screenshot](https://cloud.githubusercontent.com/assets/11681176/20627024/72c8244e-b343-11e6-9aaf-0af9bf498b8f.png)

**Comment by JimmyHurrah** [comment]
try removing the curly brackets from the import like this:
import SendBird from 'sendbird'

**Comment by ashwathan** [comment]
Thanks Jimmy. It is working.
But I want know what makes difference.

**Comment by JimmyHurrah** [comment]
@ashwathan It depends on how stuff is exported.

import without curlies imports the default exported item:
```
// a.js
export default Stuff

// b.js
import Stuff from './a.js'
```

import with curlies imports selected exports thats not defualt:
```
// a.js
export Stuff1
export Stuff2

// b.js
import { Stuff1, Stuff2 } from './a.js'
```

you can also mix the two:
```
// a.js
export Stuff1
export Stuff2
export default Stuff

//b.js
import Stuff, { Stuff1, Stuff2 } from './a.js'
```

So the key here is that stuff can be exported with the default key word.

**Comment by ashwathan** [comment]
@JimmyHurrah Thank you
