### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by ashwathan** [smilefam/SendBird-SDK-JavaScript#23]
Hi,

I am trying to integrate SendBird JS SDK in ionic-2 app. When I made connection request, I got following error message on browser console log.

-->
'XMLHttpRequest cannot load https://api-p.sendbird.com/routing/(MY_APPID). Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.

sb.connect() error object {code: 800220, message: "Connection routing failed."}'
<--

I tried to give access to 'localhost' in SendBird SETTINGS => SECURITY => Allowed Domains, but it is not getting accepted. Since hybrid apps run on localhost there is no valid domain that I can add.

Please let me know how to get this working (Allow cross origin request to sendbird server) 

Thank you

**Comment by sf-jin-ku** [comment]
@ashwathan 
Hi It should be resolved for now. 
Some sets of our routing servers weren't sending Access-Control-Allow-Origin header.
Now it should be fixed.
