### ISSUE TITLE
Upgraded from 3.0.10 to 3.0.17 and updateCurrentUserInfo stopped working

### ISSUE THREAD

**Issue by ALawliet** [smilefam/SendBird-SDK-JavaScript#25]
Was working great in 3.0.10. Without any changes to my code, I simply upgraded the library and `sb.updateCurrentUserInfo` stopped working. Doesn't seem to do anything, callback never happens, so doesn't even error. Downgraded back to 3.0.10 and it works again.

**Comment by pgarciacamou** [comment]
@ALawliet I'm using v3.0.18 and I'm noticing the same behavior; seems like it doesn't do anything.

**Comment by pgarciacamou** [comment]
`updateCurrentUserInfo` in v3.0.18 is working correctly

**Comment by ALawliet** [comment]
@pgarciacamou It honestly seems like it just doesn't do anything sometimes. I have users that register, and on that registration I call `connect` and `updateUserInfo` to sync their username so they don't join the app with messenger nickname Guest_name. It seems to work _most_ of the time, however sometimes I can see the user ends up with the Guest_name, meaning `updateUserInfo` never happened, and when I check my logs, there is nothing logged when I'm calling that function.

```
sb.connect(newUser.user_id, function(user, error) {
  sb.updateCurrentUserInfo(newUser.username, avatar.secure_url, function(response, error) {
    console.log(sendbird.currentUser);  // logs the correctly updated profile or doesn't happen
  });
});
```

**Comment by ALawliet** [comment]
@pgarciacamou Nvm, I think you're right. Using 3.0.21:

```
sb.connect(newUser.user_id, function(user, error) {
  sb.updateCurrentUserInfo(newUser.username, avatar_url, function(response, error) {
      // doesn't ever seem to do anything, but it syncs anyway... (most of the time)
  });
});
```

**Comment by ALawliet** [comment]
Okay, this is weird. 

client: v3.0.18 => callback fires
server: v3.0.18 => callback doesn't fire

server: v3.0.10 => callback fires

So on my server, I'm going to lock down v3.0.10 because it seems a lot more consistent there, and let's me know when things actually sync.

**Comment by sf-jin-ku** [comment]
@ALawliet we have a compatibility issue with NodeJS right now. We're working on the fix and should be available. client code should work well with 3.0.22
