### ISSUE TITLE
updateCurrentUserInfo error right after first connect(register).

### ISSUE THREAD

**Issue by lyw0149** [smilefam/SendBird-SDK-JavaScript#26]
![kakaotalk_photo_2016-12-07-16-06-34_7](https://cloud.githubusercontent.com/assets/10323205/20958097/28c1a85e-bc97-11e6-84d6-63779b958ec6.jpeg)

updateCurrentUserInfo error right after first connect.

Is there anyone has same error with me?

**Comment by JimmyHurrah** [comment]
Yeah, I get this error sometimes when disconnecting one user and connecting another from the same client. Im not sure whats going on.

**Comment by jherculesdt** [comment]
Same here. Any news on this? Also , it dies sometimes with an error similar to this: `.onclose of null`

**Comment by sf-jin-ku** [comment]
@jherculesdt Are you calling updateCurrentUserInfo inside of connect callback after error checking?

**Comment by jherculesdt** [comment]
@sf-craig-park yes I do it inside the connect.

**Comment by sf-jin-ku** [comment]
@jherculesdt 
This should be resolved in v3.0.23.
Let me know if you still encounter this issue!
Thanks!
