### ISSUE TITLE
Sending File Message

### ISSUE THREAD

**Issue by ashwathan** [smilefam/SendBird-SDK-JavaScript#27]
Hi,

I am trying to send a file from my device using channel.sendFileMessage call like below

channel.sendFileMessage(file, fileName, fileType, fileSize, "", "", (message, error) => {
        if (error) {
          console.error(error);
          return;
        }
      });

which takes FILE as one of the arguments but I am not clear what should be the file parameter value. Tried with file path but still the file is not getting uploaded.

Please let me know the parameters that we need to pass over here.

Thank You

**Comment by sf-jin-ku** [comment]
@ashwathan 
You can take a look at this issue!
https://github.com/smilefam/SendBird-JavaScript/issues/19
