### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by cesarwbr** [smilefam/SendBird-SDK-JavaScript#28]
Hi,

I'm using the last version (v3.0.17) of SendBird and many browsers are throwing this error: 'Cannot read property 'type' of undefined' in this part of code:
`
update(e)};i.build=function(e,t){var n,r,o,i,s,u,c;switch(e.type){case"MESG":return n=new w(e.user),r=parseInt(e.message_id),o=String(e.mess
`

**Comment by sf-jin-ku** [comment]
This should be resolved in v3.0.23.
Thanks!
Jin
