### ISSUE TITLE
Object expected

### ISSUE THREAD

**Issue by cesarwbr** [smilefam/SendBird-SDK-JavaScript#29]
Hi!

I'm using the last version (v3.0.17) of SendBird and many browsers are throwing this error: 'Object expected' in this part of code:
`statusText,response:c.responseText})},c.onerror=function(){o(null,{status:404,statusText:"There was a connection error"})}}catch(d){c=new Ac`

**Comment by cesarwbr** [comment]
It's also throwing this error: 'o is not a function'

**Comment by sf-jin-ku** [comment]
It should be fixed on the latest version
