### ISSUE TITLE
Sending file messages in React Native

### ISSUE THREAD

**Issue by alizahid** [smilefam/SendBird-SDK-JavaScript#31]
I'm using SendBird in a React Native app, and here's my code to upload images:

    sendFileMessage({
        uri: imageUriFromCameraRoll
    }, 'custom_data', callback)

However, I get the follow error:

![json-error](https://cloud.githubusercontent.com/assets/941775/21749506/212a0b78-d5b9-11e6-8fb7-1c093dd9d016.png)

It appears that the upload service returns a 404 page, instead of expected JSON, thus throwing this error.

What's the correct way to use `sendFileMessage` when there's no `File` object in React Native?

**Comment by sf-jin-ku** [comment]
https://github.com/smilefam/SendBird-JavaScript/issues/19

You can refer this issue to get the correct file json format :)
