### ISSUE TITLE
iOS APN notification payloads are different when app is closed vs app in background? Background payload is missing the data that I need.

### ISSUE THREAD

**Issue by booboothefool** [smilefam/SendBird-SDK-JavaScript#33]
```
    "react-native": "0.37.0",
    "sendbird": "^3.0.18",
```

![sendbirdnoti](https://cloud.githubusercontent.com/assets/13257645/22348784/09acadae-e3db-11e6-8e24-6f242cee53e0.jpg)

1st block is the payload when app is closed.
2nd block is the payload when app is opened, but in the background.

With the background payload, it is missing the channel_url, so I cannot navigate the user back to the channel.

**Comment by sf-jin-ku** [comment]
We've tested on RN 0.35 + SendBird 3.0.22 + react-native-push-notification 2.2.1 and it works well. (This is the combination of libraries we support in RN sample app.)
Can you test the above configuration ? @booboothefool
