### ISSUE TITLE
Upgraded from 3.0.18 to 3.0.19 and GroupChannel.markAsRead() now errors

### ISSUE THREAD

**Issue by ALawliet** [smilefam/SendBird-SDK-JavaScript#34]
![screen shot 2017-02-02 at 4 01 32 pm](https://cloud.githubusercontent.com/assets/10943083/22568225/eeab1492-e960-11e6-940e-82e99c6210d5.png)

I am even doing a check that the channel is there:
```
    if (channel) {
      channel.markAsRead();  // => error
    }
```

Working perfectly in 3.0.18 though, so I'm locking down my version.

**Comment by sf-jin-ku** [comment]
We're working on the fix now.
Sorry for the issue!

**Comment by ALawliet** [comment]
@sf-jin-ku Ah, no problem. Thanks! 👍

**Comment by sf-jin-ku** [comment]
Sorry for the issue!
New version 3.0.22 has resolved the issue.
Thanks!

**Comment by ALawliet** [comment]
@sf-jin-ku Cool!

Is there a function for `markAsRead()` with a callback? I'd like to do something like:

```
markAsRead(function(res, error) {
     // then navigate to different screen
});
```
