### ISSUE TITLE
show_read_receipt for createMyGroupChannelListQuery

### ISSUE THREAD

**Issue by kentos** [smilefam/SendBird-SDK-JavaScript#35]
I don't see a way to add `show_read_receipt` to the `createMyGroupChannelListQuery`. I could be blind. But I think there is none. How should I go about to get read_recipets on the group channel object returned to the js sdk?

I'm using react-native and would like to continue using the sdk instead of writing my own query to the platform api.

**Comment by kentos** [comment]
It seems wrong to have to do this:

`channelListQuery.limit = '20&show_read_receipt=true';`

**Comment by sf-jin-ku** [comment]
@kentos Sorry. This issue has been resolved in 3.0.25. You don't need that hack anymore :)
