### ISSUE TITLE
NODE.JS compatibility

### ISSUE THREAD

**Issue by its2mc** [smilefam/SendBird-SDK-JavaScript#4]
Hey so I tried using your module, thats available on npm with nodejs but failed spectacularly. It seems clear that there is no node compatibility, which disappoints me considering that you have the module uploaded on npm. And your documentation is inadequate. Anyway, are you guys working on an npm compatible module or is that off your schedule?

**Comment by enobufs** [comment]
@its2mc: +1

I was able to get it running with xmlhttpreq, but I cannot emulate more than one users with this. I thought the module supports `getInstance()` method but I could not find the method expose on the the module. How do I achieve the same described in your example [here](https://sendbird.gitbooks.io/sendbird-javascript-sdk/content/authentication.html)?

**Comment by its2mc** [comment]
cool approach, I will try this one. although my project is really really time constrained.. I cannot experiment too much, please let me know if you figure it out. thanks.

**Comment by sf-james-kim** [comment]
This issue is solved by lastest SDK 2.4.15.
Please download SDK version 2.4.15 or later.
