### ISSUE TITLE
Add method returning unread channel urls

### ISSUE THREAD

**Issue by rokerkony** [smilefam/SendBird-SDK-JavaScript#40]
This can come handy for the use case of visually mark unread channels in the list of all channels.

Now we have only the possibility to get the count with `getTotalUnreadChannelCount`.

Expected:
`getTotalUnreadChannelUrls`

**Comment by makskolesnikov** [comment]
@sf-craig-park
@Alchemist85K 

It would indeed be very useful to have such a method, two solutions:

1) `getUnreadChannels(callback: groupChannelCallback): void`
2) `getTotalUnreadChannelUrls()` with callback `Array<string>`

Can we expect any solution about this? :pray:

**Comment by Alchemist85K** [comment]
Thank you for your interest in SendBird SDK.
So sorry the answer is late.

Thank you for your good feedback.
I'll share and discuss it with the team.
