### ISSUE TITLE
typings are incorrect for GroupChannel

### ISSUE THREAD

**Issue by rokerkony** [smilefam/SendBird-SDK-JavaScript#41]
```ts
interface GroupChannel extends BaseChannel {
  getTotalUnreadChannelCount(callback: Function): void;
...
  getReadStatus(): Object;
}
```

First method is available on object instead of the second one is on the instance of an object.

**Comment by Alchemist85K** [comment]
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
This issue has been resolved and deployed.
