### ISSUE TITLE
How to use SendBird.d.ts

### ISSUE THREAD

**Issue by pwcremin** [smilefam/SendBird-SDK-JavaScript#43]
This is going to be a dumb issue, because I am new to Typescript, but it does not appear the declaration file is published.

I was expecting to be able to get the types by 'npm i --save @types/sendbird' is this not correct?

**Comment by rokerkony** [comment]
I don't know what is the desired way from SendBird but we do it this way:

in `typings.d.ts` we have:
```ts
/// <reference path="../node_modules/sendbird/SendBird.d.ts" />

interface Window {
    SendBird: SendBirdFactory;
}
```
where `Window` is returned by the getter `get nativeWindow (): Window` in the Angular application (accessing window directly is discouraged as it is platform independent) and used as:
```ts
constructor (windowRef: WindowRef) {
    this.sendbird = new windowRef.nativeWindow.SendBird(credentials.SendBird);
}
```

and part of our `tsconfig.ts`:
```json
"typeRoots": [
    "node_modules/@types",
    "src/typings.d.ts"
]
```

**Comment by mikebridge** [comment]
I couldn't get any of the usual imports to work after importing via npm, e.g. `import "sendbird"`, `require("sendbird")`, `import * as sendbird from "sendbird"`, `import "sendbird/SendBird"` etc.  Any idea what the syntax is supposed to be?

**Comment by tysoncadenhead** [comment]
I'm having the same issue with the typings. Typescript is saying that node_modules/sendbird/SendBird.d.ts is not a module using this import syntax:

```
import * as SendBird from 'sendbird';
```

**Comment by mobigaurav** [comment]
facing same issue .. no luck

**Comment by tomsoir** [comment]
Temp solution
Just  add *export* keyword before the all interfaces in */node_modules/sendbird/SendBird.d.ts*

**Comment by tomsoir** [comment]
Fixed by adding the `export default SendBird` at the end of SendBird.d.ts file (inside the npm package) :(

**Comment by nondefyde** [comment]
Same here. when i try to deploy an angular 2 app that needs a sendbird library to heroku or any other server it keeps bringing up this error 
error Cannot find module 'SendBird' but on my local development even when i run a production server locally to test all goes well. pls any help here

ERROR in /tmp/build_c95bd564806f778a7b0e56d1e6d905b1/src/app/_modules/chatapp/chatapp.service.ts (10,27): Cannot find module 'SendBird'.

**Comment by salguerooo** [comment]
https://github.com/smilefam/SendBird-SDK-JavaScript/pull/58

**Comment by Alchemist85K** [comment]
It should be already applied in the latest version. ( v3.0.47)

**Comment by core2root** [comment]
current version 3.0.61 and still same problem

**Comment by dercias** [comment]
Was getting this error when deploying my Angular app to Heroku: `Cannot find module 'SendBird'`.

I was able to fix it by changing imports to:

```
import * as SendBird from 'sendbird';
```

Notice the 'sendbird' in lowercase.
