### ISSUE TITLE
Internet explore 11 issue in displaying data and even listen

### ISSUE THREAD

**Issue by kumarravisingh** [smilefam/SendBird-SDK-JavaScript#44]
with version v3.0.28

The Demo of web widget which you have provided is not working on Internet Explorer 11.

Url of the sample web widget is: https://sample.sendbird.com/widget/

It is loading and logging in but there is no input option later on and also close etc buttons on chat window are not working.

Please have a look at the issue.

**Comment by Alchemist85K** [comment]
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
I tried it in Internet Explorer 11(11.786.15063.0) and it works fine.
Do you have the same problem now?
If you have the problem, please tell us which version of Internet Explorer you are using.
Thank you.
