### ISSUE TITLE
encodeParams is serializing all properties on channelListQuery.userIdsFilter array

### ISSUE THREAD

**Issue by jzgit** [smilefam/SendBird-SDK-JavaScript#45]
I'm integrating SendBird into an emberjs app and ran into an issue when querying group channels by user id.  Ember extends the Array.prototype to add a bunch of extra methods:

https://www.emberjs.com/api/classes/Ember.Array.html

and these get serialized by `encodeParams`

```
encodeParams = function(params) {
  var encodedParams = "";
  for (var i in params) {
    encodedParams += encodeURIComponent(params[i]) + ","
  }
  return encodedParams.length > 1 && (encodedParams = encodedParams.substring(0, encodedParams.length - 1)), encodedParams
},

```

I'm able to work around the issue by modifying `encodeParams` to ensure it only grabs properties directly on the array and not those up the prototype chain:
```
encodeParams = function(params) {
  var encodedParams = "";
  for (var i in params) {
    if (params.hasOwnProperty(i)) {
      encodedParams += encodeURIComponent(params[i]) + ","
    }
  }
  return encodedParams.length > 1 && (encodedParams = encodedParams.substring(0, encodedParams.length - 1)), encodedParams
},

```

Just wanted to point this out in case others run into this issue.  The actual error was "414 (Request-URI Too Large)" .  I would have submitted a pull-request but it's difficult to do with git on the minified version.

**Comment by Alchemist85K** [comment]
Thank you for your interest in SendBird SDK.
So sorry the answer is late.

It's released in version 3.0.32.
