### ISSUE TITLE
createOpenChannelListQuery lacks ability to filter by anything useful (e.g data, custom_type, Channel Metadata) 

### ISSUE THREAD

**Issue by simonwatt** [smilefam/SendBird-SDK-JavaScript#46]
From what I can tell I don't have a way set filtering options on the object returned by a call to `sb.OpenChannel.createOpenChannelListQuery();`

I can see the following properties:
limit
nameKeyword
urlKeyword

However, they don't allow me to solve any of my use cases without doing very expensive work on my client. I note that on the Platform API an optional query parameter to GET https://api.sendbird.com/v3/open_channels is custom_type (Returns channels whose custom_type matches the value given.), but an equivalent seems to be missing from the JavaScript SDK.

With the lack of filtering, I may have to loop through 100's or 1000's of records on my App and do my own filtering to display the ones I need (which might only be 2 or 3 from a set of 1000 channels). It seems much better to never send the unneeded channels to the App in the first place.

Is there a way to filter by values stored in Channel Metadata (which has the advantage it can be set in the dashboard as well as via the API)? Or failing that at least by data or custom_type (which is supported by the Platform API)?

Thanks

**Comment by simonwatt** [comment]
If my client is a paid customer is there is an unminified version of the SDK available? I'm assuming the SDK wraps the Platform API, so I could add support for custom_type filtering myself (which doesn't solve all my problems but would certainly help...).

**Comment by jzgit** [comment]
@simonwatt you can use an online tool like http://unminify.com/.  It would be helpful to have an unminified version in this repo so we could see diffs of updates to the SDK.

**Comment by tysoncadenhead** [comment]
I'm running into this issue as well. The docs are pretty unhelpful when it comes to showing how to do any sort of custom query like you can on the platform api.

**Comment by simonwatt** [comment]
@tysoncadenhead Yeah, the filtering seems very limited. It seems the platform API isn't much better? At least with the the platform API it lets you filter by 'custom_type' which the JavaScript SDK doesn't support.

At this stage it looks like I'm going to have to add my own API in the middle (so that I can make most of the filtering take place on a server) rather than calling the SendBird API directly via the JavaScript SDK.

The 'limit' parameter doesn't help much, as lets say I want to show all channels with particular meta data, I'd have to return all unfiltered channels (which could be hundreds of channels) then on the client create my filtered list... this is something that I feel should be happening on the server before it even hits the client (hence saying I'll have to build my own API in the middle).

@jzgit Yeah that is what I ended up doing. Considering the SDK seems pretty incomplete and doesn't offer everything the Platform API does... it's a shame they don't have an unminified version in this repo and allow Pull requests.

**Comment by Alchemist85K** [comment]
@simonwatt @tysoncadenhead @jzgit 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
The SDK doesn't provide all the functionality provided by the platform yet.
However, we'll do best that we can provide it as soon as possible.
Thank you.
