### ISSUE TITLE
GroupChannel doesn't contain `sendUserMessage` function

### ISSUE THREAD

**Issue by jeaye** [smilefam/SendBird-SDK-JavaScript#47]
I have two users in a distinct group channel, one of them using the Web SDK Sample and the other using my application. When I log the channel I'm getting from `sb.GroupChannel.getChannel`, I've noticed that there is no `sendUserMessage`. I can see that I'm getting channel updates and typing status changes, in my app, whenever I type something using the Web SDK Sample. However, I cannot send messages from my app (no function to do so) and I've also noticed that I'm never hitting the `onMessageReceived` handler. Instead, when my Web SDK Sample user types something, I get an `onChannelChanged` with an incremented `unreadMessageCount` and a new `lastMessage`.

Here's a log of the channel object:
```js
{ parse: [Function],
  refresh: [Function],
  update: [Function],
  updateChannel: [Function],
  invite: [Function],
  inviteWithUserIds: [Function],
  hide: [Function],
  leave: [Function],
  markAsRead: [Function],
  _sendMarkAsRead: [Function],
  getReadReceipt: [Function],
  getReadStatus: [Function],
  updateReadReceipt: [Function],
  startTyping: [Function],
  endTyping: [Function],
  invalidateTypingStatus: [Function],
  updateTypingStatus: [Function],
  isTyping: [Function],
  getTypingMembers: [Function],
  addMember: [Function],
  removeMember: [Function],
  setPushPreference: [Function],
  getPushPreference: [Function],
  channelType: 'group',
  isDistinct: true,
  unreadMessageCount: 1,
  members: 
   [ { nickname: 'contact',
       profileUrl: 'https://s.gravatar.com/avatar/6fda20d84bda6f6daaa6343262c364ef?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fco.png',
       userId: '5bf31a0e472ff5ca918cd93a5b3a77228d795c99b2552197163d6a632978bda9',
       lastSeenAt: 0,
       connectionStatus: 'online' },
     { nickname: '086V',
       profileUrl: 'https://sendbird.com/main/img/profiles/profile_39_512px.png',
       userId: '730b0a919d5f3ffdd18c122eefde99a78659987ca3aef51c34391fff45746ae3',
       lastSeenAt: 0,
       connectionStatus: 'online' } ],
  memberMap: 
   { '5bf31a0e472ff5ca918cd93a5b3a77228d795c99b2552197163d6a632978bda9': 
      { nickname: 'contact',
        profileUrl: 'https://s.gravatar.com/avatar/6fda20d84bda6f6daaa6343262c364ef?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fco.png',
        userId: '5bf31a0e472ff5ca918cd93a5b3a77228d795c99b2552197163d6a632978bda9',
        lastSeenAt: 0,
        connectionStatus: 'online' },
     '730b0a919d5f3ffdd18c122eefde99a78659987ca3aef51c34391fff45746ae3': 
      { nickname: '086V',
        profileUrl: 'https://sendbird.com/main/img/profiles/profile_39_512px.png',
        userId: '730b0a919d5f3ffdd18c122eefde99a78659987ca3aef51c34391fff45746ae3',
        lastSeenAt: 0,
        connectionStatus: 'online' } },
  lastMessage: 
   { messageType: 'user',
     messageId: 917172803,
     channelUrl: 'sendbird_group_channel_34532488_2f496608198910c6416224c413554b7c820d4e03',
     createdAt: 1499889399104,
     updatedAt: 0,
     channelType: 'group',
     message: '\\o',
     data: '',
     _sender: 
      { nickname: '086V',
        profileUrl: 'https://sendbird.com/main/img/profiles/profile_39_512px.png',
        userId: '730b0a919d5f3ffdd18c122eefde99a78659987ca3aef51c34391fff45746ae3',
        lastSeenAt: 0,
        connectionStatus: 'nonavailable' },
     reqId: '',
     customType: '',
     translations: {} },
  memberCount: 2,
  cachedReadReceiptStatus: 
   { '730b0a919d5f3ffdd18c122eefde99a78659987ca3aef51c34391fff45746ae3': 1499889396147,
     '5bf31a0e472ff5ca918cd93a5b3a77228d795c99b2552197163d6a632978bda9': 1499889376282 },
  url: 'sendbird_group_channel_34532488_2f496608198910c6416224c413554b7c820d4e03',
  name: 'Group Channel',
  coverUrl: 'https://sendbird.com/main/img/cover/cover_08.jpg',
  createdAt: 1499813285000,
  data: '',
  customType: '',
  fileUploadRequest: {},
  updatedLocal: true }
```

I must be missing something, since both of those issues are happening. I don't see anything in the docs for what it could be though.

**EDIT:** More info provided below.

I got into this scenario by using the Platform API to create a distinct group channel with two users in it. I then had each of them join that channel (one from my app and one from the Web Sample I mentioned above). I would expect that no invitation need be accepted, since the Platform API created the channel for these two users, rather than one user inviting the other.

**Comment by jeaye** [comment]
As I continue testing, I now see that the channel has two more functions:

```js
acceptInvitation: [Function],
declineInvitation: [Function],
```

1. I don't know why these weren't there before
2. My *guess* is that I need to accept the invitation before I can send to the channel

Alas, there is *no documentation on these functions* at the JS SDK reference page: https://docs.sendbird.com/javascript

Some info on this would be really great, thanks. :)

**Comment by jeaye** [comment]
Solving this problem publicly would be beneficial, so I'm leaving this ticket open, but my team has moved onto using Firebase, which has much better documentation and support. Their SDK for chat isn't quite as turn-key as SendBird's, but you're less likely to get stuck with undocumented functions and no support.

Please, SendBird folks, take this opportunity to reconsider your documentation and support. Not only for those who're already paying, but also for those who're determining if they're going to pay.

**Comment by jacks205** [comment]
Thanks @jeaye for your findings because I am in the exact same boat. I've been banging my head against the wall all day trying to figure out the correct order and behavior to use this SDK. 

Probably will check out Layer first, but will fall back with Firebase if needed.

**Comment by jeaye** [comment]
@jacks205 Still on Firebase and we're moving even more of our app to it now. Best of luck!

**Comment by shane-js** [comment]
Currently going through the same thing and surprised how quick this showed up in Google. Glad to see I wasn't the only one confused!

**Comment by shane-js** [comment]
@jeaye  @jacks205 - After going back and forth with support we figured it out - the way in which I was storing the channel was through Redux - i.e. Immutably. Apparently this serialization/deserialization strips inherited methods and GroupChannel extends from BaseChannel which has the sendUserMessage function. Therefore by not saving it Immutably (I store the open convos now in a pool on the window and draw from there, saving only the url in Redux as a pointer) it worked.

**Comment by Alchemist85K** [comment]
@jeaye @shane-js @jacks205 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
We're preparing the document that is better than the current document.
We hope that the new document will ease your inconvenience.
Thank you.
