### ISSUE TITLE
Can't add cover photo as file in Javascript SDK GroupChannel.createChannelWithUserIds

### ISSUE THREAD

**Issue by danyyacoub** [smilefam/SendBird-SDK-JavaScript#48]
Hello, 

Sending a file with the command 

GroupChannel.createChannelWithUserIds(userIds, true, groupName,groupPhoto, '', function (createdChannel, error) {});

returns 

"SendBirdException", code: 800110, message: "Invalid arguments."

GroupPhoto is a File, (checked in console) and when removed everything works correctly.

**Comment by danyyacoub** [comment]
I found the issue in Sendbird.min.js

It actually works if we replace

`if(!Array.isArray(e)||"boolean"!=typeof n||"string"!=typeof t&&null!==t&&void 0!==t||"string"!=typeof r&&h(r)&&null!==r&&void 0!==r||"string"!=typeof a&&null!==a&&void 0!==a||"string"!=typeof i&&null!==i&&void 0!==i)return void U(null,new p("Invalid arguments.",J.INVALID_PARAMETER),s);`


with 

`if(!Array.isArray(e)||"boolean"!=typeof n||"string"!=typeof t&&null!==t&&void 0!==t||"string"!=typeof a&&null!==a&&void 0!==a||"string"!=typeof i&&null!==i&&void 0!==i)return void U(null,new p("Invalid arguments.",J.INVALID_PARAMETER),s);
`

and skipping validation of the cover url (the validation is only verifying string)

**Comment by Alchemist85K** [comment]
@danyyacoub 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
This problem is solved.
Do you still have the same issue in the latest version SDK?
Please let me know if you repeat the same problem.
