### ISSUE TITLE
Cannot set property 'onmessage' of null

### ISSUE THREAD

**Issue by benjipott** [smilefam/SendBird-SDK-JavaScript#5]
with latest sdk version 2.4.13

**Comment by sf-james-kim** [comment]
Tell me about where you are using this.

**Comment by benjipott** [comment]
the source was minified so i can tell you more

**Comment by sf-james-kim** [comment]
If you are used in nodeJS server side, we don't have any plan that provide yet.
SendBird JavaScript SDK must be used in client side, not server side.
Please tell me about where you are using this.

**Comment by sf-james-kim** [comment]
this issue is solved by lastest SDK 2.4.15.
Please download SDK version 2.4.15 or later.
