### ISSUE TITLE
Is there a way to set and query user metadata from the platform API?

### ISSUE THREAD

**Issue by balajivenkatesh** [smilefam/SendBird-SDK-JavaScript#50]
Sorry, this may not be the right place for this question.

I am able to set metadata on the user from the js api and query it.
Is there a way to do the same via the platform API?

**Comment by Alchemist85K** [comment]
@balajivenkatesh 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
Please refer to this document.
https://docs.sendbird.com/platform#user_metadata_2_user_metadata
