### ISSUE TITLE
Channel members have empty metaData

### ISSUE THREAD

**Issue by balajivenkatesh** [smilefam/SendBird-SDK-JavaScript#52]
Users returned as channel members have empty metaData.
The user definitely has metaData, for example I can see it in sendbird connect callback.

**Comment by Alchemist85K** [comment]
@balajivenkatesh 
Thank you for your interest in SendBird SDK.
So sorry the answer is late. 
Do you still have the same issue in the latest version SDK?
The latest version SDK give user metaData in channel's member.
