### ISSUE TITLE
createMyGroupChannelListQuery error outside connect

### ISSUE THREAD

**Issue by balajivenkatesh** [smilefam/SendBird-SDK-JavaScript#53]
GroupChannel.createMyGroupChannelListQuery outside of userCallback of a SendBirdInstance .connect causes error "Cannot read property 'userId' of null" in React Native

**Comment by Alchemist85K** [comment]
@balajivenkatesh 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
createMyGroupChannelListQuery is using the useId of the user who is connected SendBird. We'll write the error message in a little more detail.
Thank you for your good feedback.

**Comment by sreuter** [comment]
I'm facing the same issue when I'm createMyGroupChannelListQuery.next(), as I also get a "TypeError: null is not an object (evaluating 't.userId')". I wire up the event handler in a different file where I use SendBird.getInstance() to piggyback on the already initialised/connected instance.
