### ISSUE TITLE
markAsRead() does not update channel object unreadMessageCount

### ISSUE THREAD

**Issue by balajivenkatesh** [smilefam/SendBird-SDK-JavaScript#54]
Calling markAsRead() on a channel does not update the unreadMessageCount on the channel object on the client.
I can call refresh() and wait for call to return.
But one option might be optimistically update the channel object on the client.
Or is there any other suggested way to do this?

**Comment by Alchemist85K** [comment]
@balajivenkatesh 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
you can receive event about channel change using onChannelChanged event.
Please refer to the following document link.
https://docs.sendbird.com/javascript#event_handler_3_channel_handler
