### ISSUE TITLE
Get channel metadata as part of getChannel query

### ISSUE THREAD

**Issue by balajivenkatesh** [smilefam/SendBird-SDK-JavaScript#55]
We have to do a separate query to get channel metadata after we get the channel.
Is it possible to get the metadata as part of the get channel query?
We get the metadata field of a user. But not for channel.

**Comment by Alchemist85K** [comment]
@balajivenkatesh 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
This is not available.
You must query using the channel.

**Comment by AdrianMF** [comment]
Can we reopen this?
