### ISSUE TITLE
I can not receive push notification when the message sent exceeds 400 characters

### ISSUE THREAD

**Issue by makskolesnikov** [smilefam/SendBird-SDK-JavaScript#56]
Hello, Sendbird!

First of all, I would like to say that all the methods described are fulfilled:
https://help.sendbird.com/hc/en-us/articles/115002331048

Our team uses your JavaScript solution to create chats in our service:
Web: React + sendbird v3.0.31
Mobile: React Native + sendbird v3.0.28 + react-native-push-notification

We experience some technical difficulties with receiving Push Notifications (iOS) when `mesasge: string` or `data: string` exceeds 395 characters length. In this case the messages are actually received unlike push notifications that should accompany those.
```  channel.sendUserMessage(message: string, data: string, callback: messageCallback);```

*Message sample*
```A website[1] is a collection of related web pages, including multimedia content, typically identified with a common domain name, and published on at least one web server. A website may be accessible via a public Internet Protocol (IP) network, such as the Internet, or a private local area network (LAN), by referencing a uniform resource locator (URL) that identifies the site. Websites can have many functions and can be used...```

In all the other cases we have no problem with notifications whatsoever.

Is there any limitation for values being sent and can we bypass one somehow to get a push notification on device?

**Comment by sf-craig-park** [comment]
Hi, @makskolesnikov 
Thank you for working with SendBird SDK!
Sorry for delayed response :)

To trace them, could you please specify following information?
- App ID (you can find it on our dashboard)
- User ID that should receive push notification
- (If possible) device token that you registered on our server.

Since information above are confidential, could you please send them to craig.park@sendbird.com ?

**Comment by makskolesnikov** [comment]
@sf-craig-park 
I plan to close this issue because push-notifications to APNS via HTTP/2 work fine!
Thx you Sendbird team 🎉
