### ISSUE TITLE
SDK fails to report connections errors

### ISSUE THREAD

**Issue by flochtililoch** [smilefam/SendBird-SDK-JavaScript#57]
When the network is slow or unavailable, the SDK fails to report there was a connection error. Instead, a `SendbirdException` with `{code: 0, message: null}` is thrown.

The error results from the response handler trying to `JSON.parse` on the `response` property (`undefined`) of this object:

```js
{
  status: 404,
  statusText: "There was a connection error"
}
```

<img width="676" alt="screen shot 2017-11-20 at 12 26 21 pm" src="https://user-images.githubusercontent.com/309515/33040094-e2ba7826-cdee-11e7-8b13-830198d7666d.png">

Instead I would expect an error of type `WEBSOCKET_CONNECTION_FAILED` or `NETWORK_ERROR ` maybe?

I'm testing with the SDK version `3.0.45`.

**Comment by Alchemist85K** [comment]
This has been applied since v3.0.46.
