### ISSUE TITLE
sendbird.init() uses an invalid routing URL

### ISSUE THREAD

**Issue by wesgood** [smilefam/SendBird-SDK-JavaScript#6]
I've installed the Sendbird Javascript SDK and want to initialize it in my app. 

```
$(document).ready(function() {
  // sendbird content
  sendbird.init({
    "app_id": '<%= Rails.application.secrets.sendbird_api_key =%>',
    "guest_id": '<%= current_user.sendbird_id =%>',
    "user_name": '<%= current_user.first_name =%>',
    "successFunc": function(data) {
      // Login succeeded.
      loadRecipients()
    },
    "errorFunc": function(status, error) {
      console.log(status, error);
    }
  });
})
```
The console when I run this page returns 404 Not Found error for the path https://api.sendbird.com/routing. I can confirm in the browser that this page does not exist. Why is it in the SDK? What does it do? If the URL structure of the API has changed, the SDK should change as well.

**Comment by sf-victor-lee** [comment]
Please tell me the version of your SDK.
I recommanded using the latest SDK version 2.4.17.

and, try the this URL: https://api.sendbird.com/routing/<you're app_id (not api_key)>

**Comment by wesgood** [comment]
The APP ID fix appears to be working. It's strange that the routing path is a plain 404 without a valid APP ID. Thanks for clarifying.
