### ISSUE TITLE
A `unique` option for registerGCMPushTokenForCurrentUser?

### ISSUE THREAD

**Issue by nicoqh** [smilefam/SendBird-SDK-JavaScript#60]
The Android SDK has a `unique` option for `registerGCMPushTokenForCurrentUser` which makes sure that Sendbird maintains only one FCM token for the current user.

The JavaScript SDK lacks this option. As a result we might be storing lots of tokens for any given user, many of which are stale (consider storing a token in the callback for `firebaseMessaging.onTokenRefresh()` -- invalid tokens are not removed).

I think the only way to remedy this is to manually delete the current token each time `onTokenRefresh` is run. Please correct me if I'm wrong.

Do you plan to support a `unique` option on `registerGCMPushTokenForCurrentUser`?

Either way, would you say that these two pieces of code are practically equivalent?

```
registerGCMPushTokenForCurrentUser(token, unique = true)
```
and
```
unregisterGCMPushTokenAllForCurrentUser()
registerGCMPushTokenForCurrentUser(token)
```

It's a bit hard to verify from your minified code.

**Comment by Alchemist85K** [comment]
@nicoqh 
Thank you for your interest in SendBird SDK.
So sorry the answer is late.
This feature is not provide in JavaScript SDK.
If you want to specify a unique value, you must delete all token using `unregisterGCMPushTokenAllForCurrentUser`.

**Comment by trilopin** [comment]
having multiple tokens registered will end receiving multiple times the same push?

I am receiving the same pushes in android (ios is working fine) and I don't know if my issue is related to the unique-unregistering issue .

**Comment by Alchemist85K** [comment]
@trilopin 
Thank you for your interest in SendBird SDK.
If you registered multiple tokens, you'll receive the same push.
If you want to keep only one token, delete all tokens and register.

```javascript
unregisterGCMPushTokenAllForCurrentUser()
registerAPNSPushTokenForCurrentUser(token, callback)
```

Thank you.
