### ISSUE TITLE
heroku deploy not working 

### ISSUE THREAD

**Issue by kumararun540** [smilefam/SendBird-SDK-JavaScript#62]
Hi,

I just setup java script sdk. and am able to create user from sdk very well. 
But when trying to deploy then getting error 'module' not found. 

 ```
Import code- 
import * as SendBird from 'SendBird';

ERROR in /tmp/build_de0790/src/app/app.component.ts (16,27): Cannot find module 'SendBird'.
remote:        
remote:        ERROR in ./src/app/app.component.ts
remote:        Module not found: Error: Can't resolve 'SendBird' in '/tmp/build_de0790/src/app'
remote:        @ ./src/app/app.component.ts 18:0-37
remote:        @ ./src/app/index.ts
remote:        @ ./src/main.ts
remote:        @ multi ./src/main.ts
```

using latest java script sdk version.

**Comment by Alchemist85K** [comment]
@kumararun540 
Thank you for your interest in SendBird SDK.
So sorry the answer is late. 
Do you still have the same issue in the latest version SDK?
It is difficult to confirm with the information provided at present. Please appreciate a little more details.
If you need security, please contact support@sendbird.com
