### ISSUE TITLE
sendFileMessage is not working for react-native only Android

### ISSUE THREAD

**Issue by ogelacinyc** [smilefam/SendBird-SDK-JavaScript#63]
this Is a bug report.

### Environment
OS: macOS Hight Sierra 10.13.2
Node: 8.6.0
npm: 5.6.0
Xcode: Xcode 9.0 Build version 9A235
Android Studio: 3.0.1 AI-171.4443003

### Packages:
react: 16.0.0
react-native: 0.51.0
react-native-image-picker
sendbird: 3.0.42

### Steps to Reproduce
Open Gallery or Photo Album.
Select any photo image file.
Get a ImagePicker's 'response' object.
Create a object to mapping key-value for Sendbird API.
Use 'sendFileMessage' to send a file to Sendbird.

### Actual Behavior
I had used ImagePicker to select a photo image, and send a file to Sendbird server.
And I used sendFileMessage function in Sendbrid.js, sendbird javascript-sdk.
It caused a error regardless of the file path like this

> Can currently only create a Blob from other Blobs

iOS is fine. It happen only Android, regardless android api version.

I found a [info](https://github.com/facebook/react-native/issues/16034) that react-native is not support them now.

I treid to change file type [Blob, File, FormData] and file path. 

And finally I found a bug in sendbird-sdk
Sendbird-sdk-javasciprt is using Blob, but it isn't support for Android.
I think you add polyfill to Blob object. 

sendbird library isn't open source, and was minified, then I beautified, and analyzed.
So..I don't know exactly code line number.
I checked a line by commented "*" 

I hope this is a reason for not working 'sendFileMessage', and it will update.

```
....
var t = function(e, n, t, r, a, s, i, o, l, h) {
  if (!Z.getInstance().hasLoggedIn())
    return void(i && i(null, new p("Connection should be made first.", J.CONNECTION_REQUIRED)));
  j.getInstance().checkRouting(function(n, I) {
    if (I)
      i(null, new p("Request failed.", J.REQUEST_FAILED));
    else {
      var E = v();
      E.open("POST", n.API_HOST + e, !0),
      E.setRequestHeader("SendBird", c + T),
      E.setRequestHeader("Session-Key", j.getInstance().sessionKey);
      var _ = u
        ? new u
        : new FormData;

      r && "undefined" != typeof Blob  
   //  ************* ************* ************* ************* ************* *************
        ? _.append("file", new Blob([t], {type: r}), t.name)  <--- problem is here
  //  ************* ************* ************* ************* ************* *************
        : _.append("file", t, t.name),
      s && _.append("channel_url", s);
      for (var f in a) {
        var g = parseInt(f) + 1;
        _.append("thumbnail" + g, a[f].maxWidth + "," + a[f].maxHeight)
      }
.....
```

**Comment by sf-jin-ku** [comment]
@ogelacinyc You need to install react-native-fetch-blob library to make it work in Android.
Thanks!
