### ISSUE TITLE
Export Typings interfaces

### ISSUE THREAD

**Issue by richrout** [smilefam/SendBird-SDK-JavaScript#66]
Thank's for doing typings, they're really useful.

However, it's very annoying when I want to pass or store one of your objects, I can't declare it's type.
Could you please export your public interfaces so I can make use of them?

**Comment by Alchemist85K** [comment]
@richrout 
Thank you for your interest in SendBird SDK.
So sorry the answer is late. 
Sorry, but we have not plan to public it yet.
