### ISSUE TITLE
Push Notifications in JS SDK

### ISSUE THREAD

**Issue by steveworkman** [smilefam/SendBird-SDK-JavaScript#67]
The iOS and Android SDKs all support push notifications and have documentation that describes how to set it up.

The Web has had Push Notifications for a little while, and the implementation is very similar to the Android implementation. Is it possible to subscribe for push notifications using the JS SDK, or is there a way that it can be made to work without the SDK? Are there any examples of this working out there?

[Web Fundamentals Push guide](https://developers.google.com/web/fundamentals/push-notifications/) and [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) for reference

**Comment by Alchemist85K** [comment]
@steveworkman 
Thank you for your interest in SendBird SDK.
So sorry the answer is late. 
You can use the JS SDK's `onMessageReceived` or `onChannelChanged` events to implement.
Just insert the code that activates the browser's push notification when the event arrives.
Please refer to the link below.
https://github.com/smilefam/SendBird-JavaScript/blob/master/web-sample/static/js/chat.js#L1141

**Comment by steveworkman** [comment]
@Alchemist85K this isn't what I meant.

In JS, I can create web Notifications, as I can see in the sample applications, and that works fine. What I'm trying to do is Push notifications from service workers. This allows web applications to receive notifications even if the website isn't open.

The iOS app does this via APNS, and Android via FCM, but the JS SDK doesn't have any methods to register users with the service like [iOS has](https://docs.sendbird.com/ios?_ga=2.261941711.398006096.1519050821-1484229769.1515770681#push_notifications_3_strong_step_4__strong_register_and_unregister_a_device_token_in_sendbird_sdk) and [Android has](https://docs.sendbird.com/android#push_notifications_3_strong_step_4__strong_register_fcm_registration_token_in_the_sendbird_sdk_and_parse_sendbird_fcm_messages)

Can those be added to the JS SDK?

**Comment by Alchemist85K** [comment]
@steveworkman 
We've no plans to add that function yet.
But I will share your good feedback with the team and discuss them.
Currently, we recommend using webhook to implement it.
https://docs.sendbird.com/platform#webhooks
