### ISSUE TITLE
If has too many members in group channel

### ISSUE THREAD

**Issue by phuongpt** [smilefam/SendBird-SDK-JavaScript#69]
- We have the groups with few hundreds even thousands members, so loading group channels is very slow. 
- Do you have a plan to support the adding show_member on javascript platform, same here https://docs.sendbird.com/platform#user_3_list_my_group_channels?
- it would be better if has `limit` option for getting members
Thanks.

**Comment by Alchemist85K** [comment]
@phuongpt 
Thank you for your interest in SendBird SDK.
Thank you for your good feedback.
we'll share and discuss it with the team.

**Comment by bdrobinson** [comment]
Did anything come from this? We'd really appreciate this feature.
