### ISSUE TITLE
v2.4.19 breaks in React-Native

### ISSUE THREAD

**Issue by stuartleigh** [smilefam/SendBird-SDK-JavaScript#7]
Trying to `require('http')` in react-native doesn't work. When using version 2.4.19 of sendbird I get the following error:

Unable to resolve module http from /node_modules/sendbird/SendBird.min.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/http and its parent directories

Downgrading to 2.4.18 fixes this issue.

**Comment by ippy04** [comment]
:+1 same here... RN 27.2

**Comment by tonyxiao** [comment]
Downgrading fixes the issue for me as well. If the SDK is open source I'm happy to contribute a PR. But as is there's no way around it without downgrading.

**Comment by sf-victor-lee** [comment]
There has been a problem in compatibility with the recent react-native. i will make modification soon.

**Comment by kfiroo** [comment]
@sf-victor-lee Hey, still experiencing this issue with 2.4.20
Any way we can help with this?

**Comment by ippy04** [comment]
Issue seems to still exists on latest 2.4.23

**Comment by patrickdevivo** [comment]
Seeing same issue, any updates?

**Comment by sf-jin-ku** [comment]
I apologize for all the issues but unfortunately we decided to stop supporting 2.4.x for RN platform.

We put a lot of effort on building our new V3 SDK and new RN sample is available. 

https://github.com/smilefam/SendBird-JavaScript

Please upgrade your SDK to v3.
