### ISSUE TITLE
Expo (React Native) Example + Better Push Notification Example

### ISSUE THREAD

**Issue by peterpme** [smilefam/SendBird-SDK-JavaScript#70]
Hey,

We're considering using SendBird for our new app. We are using [Expo](http://expo.io/) as our platform because it helps us build apps really quickly.

Expo has easy APIs for:
- Push notifications
- Builds & deployments
- Contact access
- Calendar Access
- Camera access
- Location

That being said, Expo doesn't support native modules. This means we have to be extra cautious with what react native components we choose.

I spent 45-60 minutes making sure I don't need native modules. Another 30 minutes making sure push notifications work correctly as well.

With Expo, you have a QR code on your repo and it automatically opens it up on your phone. No setup required. You can also create https://snack.expo.io that lets your users play with the API in the browser and automatically update changes on their phone!

I like your service so far and just wanted to share some feedback on how you could *totally* win me over 😄 

Thanks!

**Comment by Alchemist85K** [comment]
@peterpme 
Thank you for your interest in SendBird SDK.
Thank you for your good feedback.

**Comment by illyax** [comment]
Hey @peterpme How did you manage to register expo push token to SendBird?
