### ISSUE TITLE
 UserMessageParams.mentionedUserIds is set on data passed to sendUserMessage() but it doesn't seem to be getting sent to server/saved.

### ISSUE THREAD

**Issue by simonwatt** [smilefam/SendBird-SDK-JavaScript#73]
SDK v3.0.55

I'm attempting to use the newly added `UserMessageParams `feature of `channel.sendUserMessage()`. There is no documentation on your website yet, but it seems pretty clear how to use based on the definitions in the SendBird.d.ts file and the info in the change log.

I'm passing a `UserMessageParams `object as the first param to `sendUserMessage()`. If I set the `UserMessageParams.message` property it is saving okay, but any data I set on` UserMessageParams .mentionedUserIds`, and/or `UserMessageParams.mentionedUsers` seems to get lost after saving. I'm logging the object before the call to `sendUserMessage()` and the `mentionedUserIds` array seem to be set correctly, and the SDK doesn't give me an error. 

Do I need to set both the `mentionedUserIds `AND the `mentionedUsers `property? Or can i just set `mentionedUserIds`? I don't believe this is the problem though as I've tried different combinations.

If I log the message after retrieving all messages again then the `message.mentionedUsers` property is an empty array (the message text saves fine though). Likewise if i log the message payload on the `open_channel:message_send` webhook there is also no `mentionedUserIds` data.

I can provide sample code, but before going to that effort I'd at least like to know if this is even meant to be working yet.

**Comment by Alchemist85K** [comment]
@simonwatt 
If you use userId or Users, the message will contain mentionedUsers for valid users only.
Please check the sample code below and check user valid.

```
/** UserMessageParams - userId */
var userMessageParams = new sb.UserMessageParams();
userMessageParams.message = 'message'; // required
userMessageParams.targetLanguages = ['ko', 'en'];
userMessageParams.data = 'data';
userMessageParams.customType = 'customType';
userMessageParams.mentionedUserIds = ['userId1', 'userId2'];

/** UserMessageParams - userId */
var userMessageParams = new sb.UserMessageParams();
userMessageParams.message = 'message'; // required
userMessageParams.targetLanguages = ['ko', 'en'];
userMessageParams.data = 'data';
userMessageParams.customType = 'customType';
userMessageParams.mentionedUsers = [User1, User2];

/** sendUserMessage with mention */
var userMessageParams = new sb.UserMessageParams();
userMessageParams.message = 'message';
userMessageParams.mentionedUserIds = ['userId1', 'userId2'];
channel.sendUserMessage(userMessageParams, function(res, err) {
  // do something...
});
```

**Comment by simonwatt** [comment]
@Alchemist85K Thanks for the code sample. I had a typo on a property name which was causing the issue. It's now persisting correctly, and the mentionedUsers array on the message is populated correctly when reloading data.

Is the mentionedUserIds going to be added to the MESG payload on the `open_channel:message_send` web hook? Currently it doesn't seem to be there.

**Comment by Alchemist85K** [comment]
@simonwatt 
The mentioned user was added as "mentioned_users" key on message payload.
If you has still same issue, please tell me your `APP_ID` and mentioned `userID`.
Thank you.

**Comment by simonwatt** [comment]
@Alchemist85K I'm now seeing mentioned_users in the webhook data. Issue was that I was expecting it as a property on payload (when it's a level higher) so my deserialization was failing since it couldn't find it. Thanks!

**Comment by simonwatt** [comment]
I was expecting:

```
{
  "app_id": "xxx",
  "category": "open_channel:message_send",
  "type": "MESG",
  "channel": {
    "channel_url": "sendbird_open_channel_xxx",
    "name": "Test"
  },
  "sender": {
    "user_id": "auth0|xxx",
    "nickname": "Simon3 Watt3",
    "profile_url": "https://xxx"
  },
  "payload": {
    "message_id": "1441178500",
    "created_at": "1520990925884",
    "custom_type": "",
    "message": "moo",
    "data": "",
    "translations": []
    "mentioned_users": [
     {
      "user_id": "xxx",
      "nickname": "xxx Admin",
      "profile_url": "//xxx/dashboard/icon-user-profile-02.svg",
      "metadata": []
     },
     {
      "user_id": "xxx",
      "nickname": "Simon Developer",
      "profile_url": "//xxx/dashboard/icon-user-profile-02.svg",
      "metadata": []
    }
   ]
  } 
}
```
When actually it was coming in like:

```
{
  "app_id": "xxx",
  "category": "open_channel:message_send",
  "type": "MESG",
  "channel": {
    "channel_url": "sendbird_open_channel_xxx",
    "name": "Test"
  },
  "sender": {
    "user_id": "auth0|xxx",
    "nickname": "Simon3 Watt3",
    "profile_url": "https://xxx"
  },
  "payload": {
    "message_id": "1441178500",
    "created_at": "1520990925884",
    "custom_type": "",
    "message": "moo",
    "data": "",
    "translations": []
  },
  "mentioned_users": [
    {
      "user_id": "xxx",
      "nickname": "xxx Admin",
      "profile_url": "//xxx/dashboard/icon-user-profile-02.svg",
      "metadata": []
    },
    {
      "user_id": "xxx",
      "nickname": "Simon Developer",
      "profile_url": "//xxx/dashboard/icon-user-profile-02.svg",
      "metadata": []
    }
  ]
}
```
