### ISSUE TITLE
Sendbird still can't be loaded via requireJS

### ISSUE THREAD

**Issue by steveworkman** [smilefam/SendBird-SDK-JavaScript#75]
This is an update to #64 which suggested a new way to define the SendBird code and load it through requireJS.

There was a change in the 3.0.55 version which swapped the module definition syntax to a new version. However, this has not worked.

Using v3.0.59, I now can't load the SendBird module at all. RequireJS retrieves it, however, it cannot understand the format and it exits silently.

I've tried the previous trick of adding the UMD definition steps, but this doesn't work now because of other changes.

Can you look in to this please? I don't understand why this doesn't work!

**Comment by imju** [comment]
Hi Steve,
We were able to resolve the issue and it is incorporated to a new version of JS SDK.  
Please download and try it out.
Thanks,
Imju

**Comment by steveworkman** [comment]
Thanks a lot, that's working now.
