### ISSUE TITLE
[React Native]: Version `3.0.46+` not working on Android

### ISSUE THREAD

**Issue by panz3r** [smilefam/SendBird-SDK-JavaScript#77]
After integrating `SendBird JS SDK` in a `ReactNative` project I found a strange behaviour.
When running on `iOS` everything is OK, but on `Android` as soon as I run 
```js
sb.connect(userId, function(user, error) {
```
the following error is thrown:
```
Cannot read property 'connect' of null
<unknown>
Sendbird.min.js:8:14207
```

This happens for every version newer than v`3.0.45`.

**Comment by Alchemist85K** [comment]
Hi @panz3r .
So sorry the answer is late.
Are you still having problem with the latest version v3.0.63?
Thank you for your interest in SendBird SDK.

**Comment by panz3r** [comment]
Hi @Alchemist85K ,

Unfortunately yes, just tried with `v3.0.64` and getting the same error
```
Cannot read property 'connect' of null

<unknown>
Sendbird.min.js:9:16897
```

**Comment by chrisallo** [comment]
If you don't mind, could you bring the code snippet how you initialized sb? It seems like sb is not initialized properly. var sb = new SendBird({ appId: APP_ID }) could assign null to sb where APP_ID is not provided. Or another possibility is that sb.connect is called BEFORE sb is defined.

**Comment by chrisallo** [comment]
You can check out RN Redux sample and find the difference. RN Redux sample works fine in both Android and iOS :)

**Comment by panz3r** [comment]
Hi @chrisallo ,

I recently tried the RN Redux sample and it works just fine even with the newer `sendbird-SDK` version on `Android`.

So I can consider this issue as closed.
Thanks.
