### ISSUE TITLE
Use a different websocket library (ws)

### ISSUE THREAD

**Issue by haykam821** [smilefam/SendBird-SDK-JavaScript#83]
Currently this SDK does not work on Node.js v10.x.x because [`websocket`](https://github.com/theturtle32/WebSocket-Node), a dependency of yours, only seems to work on Node.js v8.x.x or lower. However, its alternative, [`ws`](https://github.com/websockets/ws) is more maintained, is [more popular](https://www.npmtrends.com/websocket-vs-ws), and supports more versions. Can you switch from `websocket` to `ws` to regain compatibility with the latest version of Node.js?

**Comment by Alchemist85K** [comment]
Hi~ @haykam821 .
Thank you for your interest in SendBird SDK.
It's been solved in the latest version. 
Please use the latest version.
