### ISSUE TITLE
React Native: N.getApplicationId is not a function

### ISSUE THREAD

**Issue by nullfox** [smilefam/SendBird-SDK-JavaScript#87]
I'm currently trying to implement the SendBird SDK into a new React Native project.

Anytime I initialize the SDK by doing the following:

```
const chatClient = new SendBird({
  appId: '950EXXXX-XXXX-XXXX-XXXX-8F90BE6XXXX',
});
```

I get the React Native red screen of death with the following:
```
TypeError: N.getApplicationId is not a function
```

SendBird version 3.0.81
React Native version 0.57.1

**Comment by nullfox** [comment]
Hi @Alchemist85K I called `const chatClient = new SendBird()` in the componentDidMount() of my React Native component. I never call getApplicationId() anywhere, that's an error that seems to generated within the library.

The error `TypeError: N.getApplicationId is not a function` is thrown anytime I call `new SendBird()`

**Comment by Alchemist85K** [comment]
@nullfox 
Would you like to try the code below?

```
import React, {Component} from 'react';
import {StyleSheet, Text, View} from 'react-native';
import SendBird from 'sendbird';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      sb: null
    }
  }

  componentDidMount() {
    const appId = '4D7D6D8B-E668-485E-9A72-FFB166E6257F';
    const sb = new SendBird({ appId });
    this.setState({ sb });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Welcome to React Native!</Text>
        <Text>SendBird Application ID: {this.state.sb === null ? '' : this.state.sb.getApplicationId()} </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by nullfox** [comment]
@Alchemist85K Thank you for the reply - it turns out that an errant, left over piece of code was causing trouble in the babel-ized/compiled code.

I was able to get the client working however, I am seeing a WebSocket error without much infor
```{name: "SendBirdException", code: 800210, message: "Websocket connection failed."}```

**Comment by Alchemist85K** [comment]
@nullfox Could you tell me your APP_ID, userID, and accessToken? I'll try it with the same data.
