### ISSUE TITLE
Latest version does not work with React Native

### ISSUE THREAD

**Issue by gamedolphin** [smilefam/SendBird-SDK-JavaScript#88]
The latest version and versions since 3.0.74 do not compile on react  native since the ws package isn't supposed to be run outside of a node environment and throws multiple missing modules errors.. In React Native and browser environments, you are supposed to use the native Websocket object to connect to the server.  There's also a dependence on 'http' module which does not exist outside of node environment.

**Comment by lucsky** [comment]
I've been banging my head on the wall for hours with this today and reached the same conclusion. You beat me to it by 2 hours 😄

**Comment by gamedolphin** [comment]
> I've been banging my head on the wall for hours with this today and reached the same conclusion. You beat me to it by 2 hours smile

Use 3.0.61. That seems to work for now.

**Comment by lucsky** [comment]
@gamedolphin yes, using a version prior to 3.0.74 works for me, I'm using 3.0.73.

**Comment by chrisallo** [comment]
Hi all, would you try the latest version (which is 3.0.84)? It might be a fix.

**Comment by lucsky** [comment]
@chrisallo Confirmed. 3.0.84 works for me in React Native.

**Comment by gamedolphin** [comment]
Thank you. It works. :+1:
