### ISSUE TITLE
groupChannel.startTyping and groupChannel.endTyping does not trigger handler onTypingStatusUpdated

### ISSUE THREAD

**Issue by teod** [smilefam/SendBird-SDK-JavaScript#89]
The onTypingStatusUpdated ChannelHandler is not triggering when calling groupChannel.startTyping and groupChannel.endTyping
```javascript
  var handler = new sb.ChannelHandler()
  handler.onTypingStatusUpdated = (groupChannel) => {
    console.log(groupChannel)
  }

    sb.GroupChannel.getChannel(URL, (channel, error) => {
      if (error) {
       return
      }

      channel.startTyping()

      window.setTimeout(() => channel.endTyping(), 1000)
   })
```

**Comment by Alchemist85K** [comment]
@teod 
Thank you for your interest in SendBird SDK. :)
You have to register a function that you have override using `addChannelHandler()`.
And, those who call `startTyping()` or `endTyping()` do not receive `onTypingStatusUpdated` event.

**Comment by teod** [comment]
@Alchemist85K, Thanks ! sorry I missed that part from the documentation.
