### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by fozzle** [smilefam/SendBird-SDK-JavaScript#9]
Any possibility to have support for promises added on top of callbacks? I can obviously promisify it myself but it'd be nice to be able to skip that step altogether.

New major version of the SDK looks great. Lots of new features I really needed. Can't wait for the npm release. Thanks.

**Comment by Alchemist85K** [comment]
Thank you for your interest in SendBird SDK.
So sorry the answer is late.

We plan to provide it.
We'll do best that we can provide it as soon as possible.
Thank you.

**Comment by haykam821** [comment]
@Alchemist85K, is this issue still being worked on? It's been 8 months and no update since [v3.0.53](https://github.com/smilefam/SendBird-SDK-JavaScript/releases/tag/v3.0.53) includes support for promises.

**Comment by Alchemist85K** [comment]
It does not support yet.
