### ISSUE TITLE
npm package doesn't work on linux 

### ISSUE THREAD

**Issue by teod** [smilefam/SendBird-SDK-JavaScript#90]
`import * as SendBird from 'SendBird'`

 because of the camelcase import this fails using webpack on linux (case-sensitive) systems. This does work on osX correctly.

**Comment by Alchemist85K** [comment]
@teod 
Could you change to "sendbird" and try it?
```
import * as SendBird from 'sendbird'
```

**Comment by teod** [comment]
@Alchemist85K 
I tried that, I'm not really sure about this, at first it was failing with a type error, after a clean npm install it started working with lowercase as well. I guess we can close this issue.
Thank you!
