### ISSUE TITLE
NPM package don't have source-map

### ISSUE THREAD

**Issue by rubensolx** [smilefam/SendBird-SDK-JavaScript#91]
Hello,
I'm using the npm package and noted that there's no source-map on the package.
Currently is throwing an exception from within the library but there's no way to know exactly is, and a source-map would help a lot on this.

**Comment by chrisallo** [comment]
Hi @rubensolx,
SendBird SDK doesn't provide source-map because the code could be decompiled and revealed with source-map which is stated as PROHIBITED by license. Basically SDK throws SendBirdException on internal error with error code and message, so you'd better contact us with the error.

**Comment by rubensolx** [comment]
Strange doing that for JS, because with one click on google dev-tools can format the code and all the logic is visible. I mean, the entire JS concept is that you can't hide anything on it, but anyway, no worries.
Only in the API leve it seems to respond with error messages, but not common JS exceptions 🤔 

No worries at all, thanks for the response :)
