### ISSUE TITLE
 "Not owner" error, even if "operator" role is assigned

### ISSUE THREAD

**Issue by Dimasik911** [smilefam/SendBird-SDK-JavaScript#96]
I have assigned an operator to a chat but he can't update somebody's else messages. His value for myRole in user object is "operator". On update it throws an error "Not owner"

What could be an issue?

**Comment by sf-craig-park** [comment]
Hi, this is Craig, an infrastructure engineer at SendBird.

Could you please specify the following items:
- `APP_ID` that you're currently working with
- `user_id` and the `message_id`

I'll figure it out if you share those to me.

Thanks!

**Comment by Alchemist85K** [comment]
Hi~ @Dimasik911 

Even if a user is currently an operator, the user can't update a message of another user using SDK.
Operators can use functions such as ban, mute, etc.
If you want to update a message that sent by other users, please uses the API.

https://docs.sendbird.com/platform/messages#3_edit_the_message

Thank you for your interest in SendBird SDK. :)
